"""add PPA bundle/project tables

Revision ID: 4cdcfa48ce3e
Revises: 25bfd00998ba
Create Date: 2025-10-09 15:01:01.021628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cdcfa48ce3e'
down_revision: Union[str, Sequence[str], None] = '25bfd00998ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ppa_bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('voltage', sa.Enum('HIGH', 'EHV', 'LOW', name='voltagelevel'), nullable=False),
    sa.Column('area', sa.String(length=32), nullable=False),
    sa.Column('prev_supplier_plan', sa.String(length=120), nullable=True),
    sa.Column('contract_start_date', sa.Date(), nullable=True),
    sa.Column('quote_valid_days', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.Date(), nullable=True),
    sa.Column('request_due_date', sa.Date(), nullable=True),
    sa.Column('quote_status', sa.Enum('DRAFT', 'SUBMITTED', 'PRICED', 'EXCEL_READY', name='quotestatus'), nullable=False),
    sa.Column('offer_status', sa.Enum('NONE', 'OFFERED', 'WON', 'LOST', name='offerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ppa_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('capacity_mw', sa.Float(), nullable=False),
    sa.Column('ppa_unit_price_yen_per_kwh', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['ppa_bundles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ppa_projects_bundle_id'), 'ppa_projects', ['bundle_id'], unique=False)
    op.create_table('ppa_supply_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('supply_point_number', sa.String(length=64), nullable=True),
    sa.Column('contract_kw', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['ppa_bundles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ppa_supply_points_bundle_id'), 'ppa_supply_points', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_ppa_supply_points_supply_point_number'), 'ppa_supply_points', ['supply_point_number'], unique=False)
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    op.drop_index(op.f('ix_ppa_supply_points_supply_point_number'), table_name='ppa_supply_points')
    op.drop_index(op.f('ix_ppa_supply_points_bundle_id'), table_name='ppa_supply_points')
    op.drop_table('ppa_supply_points')
    op.drop_index(op.f('ix_ppa_projects_bundle_id'), table_name='ppa_projects')
    op.drop_table('ppa_projects')
    op.drop_table('ppa_bundles')
    # ### end Alembic commands ###
