"""init core domain tables

Revision ID: f87c8c64ff32
Revises: 19162e2abe1f
Create Date: 2025-10-09 13:26:29.750887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87c8c64ff32'
down_revision: Union[str, Sequence[str], None] = '19162e2abe1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agencies_number'), 'agencies', ['number'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('supply_point_number', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('negotiated_power_kw', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('UNDER_CONTRACT', 'RECONTRACT_ESTIMATE', 'RECONTRACTED', name='contractstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supply_point_number', 'end_date', name='uq_contract_spn_end')
    )
    op.create_index(op.f('ix_contracts_customer_id'), 'contracts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_contracts_supply_point_number'), 'contracts', ['supply_point_number'], unique=False)
    op.create_table('recontract_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('desired_quote_date', sa.Date(), nullable=False),
    sa.Column('quote_effective_days', sa.Enum('DAYS_30', 'DAYS_60', name='quoteeffectivedays'), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recontract_estimates_customer_id'), 'recontract_estimates', ['customer_id'], unique=False)
    op.create_table('ancillary_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('STANDBY_POWER', 'STANDBY_LINE', 'PRIVATE_POWER_SUPPLY', 'NON_FOSSIL_CERT', 'RENEWABLE_LEVY_REDUCTION', 'ENECLOUD_DISCOUNT', name='ancillarytype'), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ancillary_contracts_contract_id'), 'ancillary_contracts', ['contract_id'], unique=False)
    op.create_table('recontract_plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimate_id', sa.Integer(), nullable=False),
    sa.Column('capacity_mw', sa.Float(), nullable=False),
    sa.Column('ppa_unit_price_yen_per_kwh', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['estimate_id'], ['recontract_estimates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recontract_plants_estimate_id'), 'recontract_plants', ['estimate_id'], unique=False)
    op.create_table('recontract_supply_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimate_id', sa.Integer(), nullable=False),
    sa.Column('supply_point_number', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['estimate_id'], ['recontract_estimates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recontract_supply_points_estimate_id'), 'recontract_supply_points', ['estimate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recontract_supply_points_estimate_id'), table_name='recontract_supply_points')
    op.drop_table('recontract_supply_points')
    op.drop_index(op.f('ix_recontract_plants_estimate_id'), table_name='recontract_plants')
    op.drop_table('recontract_plants')
    op.drop_index(op.f('ix_ancillary_contracts_contract_id'), table_name='ancillary_contracts')
    op.drop_table('ancillary_contracts')
    op.drop_index(op.f('ix_recontract_estimates_customer_id'), table_name='recontract_estimates')
    op.drop_table('recontract_estimates')
    op.drop_index(op.f('ix_contracts_supply_point_number'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_customer_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('plans')
    op.drop_index(op.f('ix_agencies_number'), table_name='agencies')
    op.drop_table('agencies')
    # ### end Alembic commands ###
